# Configuration file.
# Pretty simple at the moment, but should get a lot better soon.

# Project name has effect only on the name of the generated binary
project_name = "example"

# This compiler will be invoked internally.
# This can be changed here, most compilers support the same set of flags.
compiler = "clang"

[options]
# Here we can set custom compiler and linker flags.
c_flags = "-Wall -Wextra -O2"

# If we wanted to change the link flags, you would do: `link_flags = ""`

[dependencies]